name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Trigger release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare repository
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git fetch --prune --unshallow

      - name: Install
        run: npm ci

      - name: Bundle
        run: npm run bundle

      - name: Lint
        run: npm run lint

      - name: Prepare npm config for github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat <<EOF > ~/.npmrc
          //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}
          @cliqz:registry=https://npm.pkg.github.com
          EOF
      - name: Create release
        run: npm publish
