name: Tests

on:
  pull_request:
  push:

jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [12, 14, 18, 20, 21]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: npm ci

      - name: Bundle
        run: npm run bundle

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run ci-test
